@echo off
title Iniciando a API.
echo .............................................................
echo ................. Gerador de metricas de navios ...........
echo .............................................................
env\Scripts\activate && python Main/massops.py