@echo off
title Iniciando a API.
echo .............................................................
echo ................. Gerador de planilhas de viagens ...........
echo .............................................................
echo
conda activate C:\Users\lucas.rocha\GitRepos\MTraffic\BR-MarineTraffic\Codenv && python Main/functions.py 